### ISSUE TITLE
Create a magical documentation and conduct code

### ISSUE THREAD

**Issue by giovannicruz97** [giovannicruz97/magic#1]
**Hey guys!** I've been working alone on this project. I really would like a little help 😄. I don't know how to create a beautiful documentation, conduct and contribution code. So, could you help me?

**Comment by gustavoper** [comment]
Sure, we should start adding some PHPDoc tags on code! =)

**Comment by msaeef** [comment]
I can work on this issue; Sphinx tool can be used to make documentation

**Comment by giovannicruz97** [comment]
Oh thanks guys! ( @gustavoper  and @msaeef ). I don't feel like I'm alone anymore haha!

**Comment by dev-haykay** [comment]
@giovannicruz97. Do you want us to document the code.

**Comment by giovannicruz97** [comment]
@dev-haykay Yes, I want some help to document the code and the project itself.

**Comment by dev-haykay** [comment]
@giovannicruz97 I'll start working on the code documentation.
