### ISSUE TITLE
Improve route system

### ISSUE THREAD

**Issue by giovannicruz97** [giovannicruz97/magic#3]
Hey guys, what's up? I've been looking for our Router class and I realized that it's kinda ugly haha. What do you guys think we should improve?

**Comment by AdityaK-sophos** [comment]
I can try improving its look, if that's cool with you?

**Comment by ItachiUchiha1998** [comment]
I will like to help you with.

**Comment by giovannicruz97** [comment]
Thanks for the feedback guys! All PRs are welcome! 😄
